-- DROP TABLE Statements
DROP TABLE "TB_ROOM";
DROP TABLE "TB_ROOM_BOOKING";
DROP TABLE "TB_BUSINESS";
DROP TABLE "TB_PICTURE";
DROP TABLE "TB_MEMBER";
DROP TABLE "TB_REVIEW";
DROP TABLE "TB_TOUR_PICTURE";
DROP TABLE "TB_TOUR";
DROP TABLE "TB_WISHLIST";
DROP TABLE "TB_RENTCAR";
DROP TABLE "TB_CAR_BOOKING";
DROP TABLE "TB_CATEGORY";

-- CREATE TABLE Statements
CREATE TABLE "TB_ROOM" (
	"room_num"	NUMBER		NOT NULL,
	"room_max"	NUMBER		NOT NULL,
	"room_name"	VARCHAR2(255)	NOT NULL,
	"room_price"	NUMBER		NOT NULL,
	"checkin"	VARCHAR2(255)	NOT NULL,
	"checkout"	VARCHAR2(255)	NOT NULL,
	"room_info"	VARCHAR2(255)	NOT NULL,
	"bu_id"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("room_num")
);

CREATE TABLE "TB_ROOM_BOOKING" (
	"booking_num"	VARCHAR2(255)	NOT NULL,
	"room_num"	NUMBER		NOT NULL,
	"email"	VARCHAR2(255)	NOT NULL,
	"checkin"	DATE		NOT NULL,
	"checkout"	DATE		NOT NULL,
	"status"	NUMBER		NOT NULL,
	"payment"	VARCHAR2(255)	NOT NULL,
	"price"	VARCHAR2(255)	NOT NULL,
	"Field10"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("booking_num")
);

CREATE TABLE "TB_BUSINESS" (
	"bu_id"	VARCHAR2(255)	NOT NULL,
	"email2"	VARCHAR2(255)	NOT NULL,
	"bu_tel"	VARCHAR2(255)	NOT NULL,
	"bu_address"	VARCHAR2(255)	NOT NULL,
	"bu_title"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("bu_id")
);

CREATE TABLE "TB_PICTURE" (
	"location"	VARCHAR2(255)	NOT NULL,
	"room_num"	NUMBER		NULL,
	"bu_id"	VARCHAR2(255)	NULL,
	PRIMARY KEY ("location")
);

CREATE TABLE "TB_MEMBER" (
	"email"	VARCHAR2(255)	NOT NULL,
	"password"	VARCHAR2(255)	NOT NULL,
	"tel"	VARCHAR2(255)	NOT NULL,
	"name"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("email")
);

CREATE TABLE "TB_REVIEW" (
	"rev_num"	NUMBER		NOT NULL,
	"email2"	VARCHAR2(255)	NOT NULL,
	"ac_name"	VARCHAR2(255)	NOT NULL,
	"content"	VARCHAR2(255)	NOT NULL,
	"review_date"	DATE		NOT NULL,
	"score"	NUMBER		NOT NULL,
	PRIMARY KEY ("rev_num")
);

CREATE TABLE "TB_TOUR_PICTURE" (
	"location"	VARCHAR2(255)	NOT NULL,
	"ac_name"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("location")
);

CREATE TABLE "TB_TOUR" (
	"ac_name"	VARCHAR2(255)	NOT NULL,
	"ac_address"	VARCHAR2(255)	NOT NULL,
	"tr_info"	VARCHAR2(255)	NOT NULL,
	"act_id"	NUMBER		NOT NULL,
	"Field"	NUMBER		NOT NULL,
	PRIMARY KEY ("ac_name")
);

CREATE TABLE "TB_WISHLIST" (
	"ac_name"	VARCHAR2(255)	NOT NULL,
	"email"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("ac_name", "email")
);

CREATE TABLE "TB_RENTCAR" (
	"car_num"	VARCHAR2(255)	NOT NULL,
	"car_id"	VARCHAR2(255)	NOT NULL,
	"car_name"	VARCHAR2(255)	NOT NULL,
	"car_price"	NUMBER		NOT NULL,
	"car_info"	VARCHAR2(255)	NULL,
	PRIMARY KEY ("car_num")
);

CREATE TABLE "TB_CAR_BOOKING" (
	"car_num"	VARCHAR2(255)	NOT NULL,
	"car_recieve_place"	VARCHAR2(255)	NOT NULL,
	"car_return_place"	VARCHAR2(255)	NOT NULL,
	"car_time_start"	DATE		NOT NULL,
	"car_time_over"	DATE		NOT NULL,
	"email"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("car_num")
);

CREATE TABLE "TB_CATEGORY" (
	"ac_name"	VARCHAR2(255)	NOT NULL,
	"category"	VARCHAR2(255)	NOT NULL,
	PRIMARY KEY ("ac_name", "category")
);

-- ALTER TABLE Statements (Constraints)
ALTER TABLE "TB_ROOM" ADD CONSTRAINT "FK_TB_BUSINESS_TO_TB_ROOM" FOREIGN KEY ("bu_id") REFERENCES "TB_BUSINESS" ("bu_id");

ALTER TABLE "TB_ROOM_BOOKING" ADD CONSTRAINT "FK_TB_ROOM_TO_TB_ROOM_BOOKING" FOREIGN KEY ("room_num") REFERENCES "TB_ROOM" ("room_num");
ALTER TABLE "TB_ROOM_BOOKING" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_ROOM_BOOKING" FOREIGN KEY ("email") REFERENCES "TB_MEMBER" ("email");

ALTER TABLE "TB_BUSINESS" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_BUSINESS" FOREIGN KEY ("email2") REFERENCES "TB_MEMBER" ("email");

ALTER TABLE "TB_PICTURE" ADD CONSTRAINT "FK_TB_ROOM_TO_TB_PICTURE" FOREIGN KEY ("room_num") REFERENCES "TB_ROOM" ("room_num");
ALTER TABLE "TB_PICTURE" ADD CONSTRAINT "FK_TB_BUSINESS_TO_TB_PICTURE" FOREIGN KEY ("bu_id") REFERENCES "TB_BUSINESS" ("bu_id");

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REVIEW" FOREIGN KEY ("email2") REFERENCES "TB_MEMBER" ("email");
ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_TOUR_TO_TB_REVIEW" FOREIGN KEY ("ac_name") REFERENCES "TB_TOUR" ("ac_name");

ALTER TABLE "TB_TOUR_PICTURE" ADD CONSTRAINT "FK_TB_TOUR_TO_TB_TOUR_PICTURE" FOREIGN KEY ("ac_name") REFERENCES "TB_TOUR" ("ac_name");

ALTER TABLE "TB_WISHLIST" ADD CONSTRAINT "FK_TB_TOUR_TO_TB_WISHLIST" FOREIGN KEY ("ac_name") REFERENCES "TB_TOUR" ("ac_name");
ALTER TABLE "TB_WISHLIST" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_WISHLIST" FOREIGN KEY ("email") REFERENCES "TB_MEMBER" ("email");

ALTER TABLE "TB_CAR_BOOKING" ADD CONSTRAINT "FK_TB_RENTCAR_TO_TB_CAR_BOOKING" FOREIGN KEY ("car_num") REFERENCES "TB_RENTCAR" ("car_num");
ALTER TABLE "TB_CAR_BOOKING" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_CAR_BOOKING" FOREIGN KEY ("email") REFERENCES "TB_MEMBER" ("email");

ALTER TABLE "TB_CATEGORY" ADD CONSTRAINT "FK_TB_TOUR_TO_TB_CATEGORY" FOREIGN KEY ("ac_name") REFERENCES "TB_TOUR" ("ac_name");
